### ISSUE TITLE
GCD and LCM

### ISSUE THREAD

**Issue by Sayak-Karar-2581** [Suranjan2002/Hacktoberfest-2021-contribute#20]
Two integers **A** and **B** are the inputs. Write a program to find GCD and LCM of **A** and **B**.

---
### Input
The first line contains an integer **T**, the total number of test cases. Then follow **T** lines, each line contains an integer **A** and **B**.

---
### Output
Display the GCD and LCM of **A** and **B** separated by space respectively. The answer for each test case must be displayed in a new line.

---
### Constraints
- 1 **≤ T ≤** 100
- 1 **≤ A,B ≤** 1000

---
### Example
**Input**
```
3 
120 140
10213 312
10 30
```
**Output**
```
20 840
1 3186456
10 30
```
---
### Languages	
- JAVA
- C
- C++
- PYTHON

**Comment by Ankitlenka26** [comment]
I can work on this in C++

**Comment by GarvitV957** [comment]
I have created this program using recursion in cpp. Hope this would work fine.
Thanks and regards
Garvit

**Comment by Sockalingam29** [comment]
Okay! I will create in Java
