### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by Suranjan2002** [Suranjan2002/Hacktoberfest-2021-contribute#26]
You're given an integer **N**. Write a program to check whether a number is Palindrome or not

---
### Input
The first line contains an integer **T**, the total number of test cases. Then follow **T** lines, each line contains an integer **N**.

---
### Output
For each test case, display whether the number is a palindrome or not

---
### Constraints
- 1 ≤ T ≤ 1000
- 1 ≤ N ≤ 10000

---
### Example
**Input**\
```
2
1001
1234
```

**Output**\
```
Palindrome Number
Not a Palindrome Number
```

---
### Languages
- JAVA
- C
- C++
- PYTHON

**Comment by Sayak-Karar-2581** [comment]
You solve this as it is. We will merge it if it's well enough.
