### ISSUE TITLE
Sum of Digits

### ISSUE THREAD

**Issue by Sayak-Karar-2581** [Suranjan2002/Hacktoberfest-2021-contribute#5]
You're given an integer **N**. Write a program to calculate the sum of all the digits of **N**.

---
### Input
The first line contains an integer **T,** the total number of test cases. Then follow **T** lines, each line contains an integer **N**.

---
### Output
For each test case, calculate the sum of digits of **N**, and display it in a new line.

---
### Constraints
- 1 **≤ T ≤** 1000
- 1 **≤ N ≤** 1000000

---
### Example
**Input**
```
3 
12345
31203
2123
```
**Output**
```
15
9
8
```
---
### Languages	
- JAVA
- C
- C++
- PYTHON

**Comment by tausiq2003** [comment]
I can solve it assign me

**Comment by Syntax0002** [comment]
can u please assign this issue to me @Suranjan2002
