### ISSUE TITLE
Check Even or Odd

### ISSUE THREAD

**Issue by Sinjini46** [Suranjan2002/Hacktoberfest-2021-contribute#51]
You're given an integer **N**. Write a program to check whether the integer is an **Even** number or a **Odd**.

---
### Input
The first line contains an integer **T**, the total number of test cases. Then follow **T** lines, each line contains an integer **N**.

---
### Output
For each test case, check whether the number is **Even** or **Odd**. If it is **Even**, then display **"EVEN"** or else display **"ODD"**, in a new line (quotes for clarity).

---
### Constraints
- 1 **≤ T ≤** 100
- 1 **≤ N ≤** 1000

---
### Example
**Input**
```
3 
145
1034
40585
```
**Output**
```
ODD
EVEN
ODD
```
---
### Languages	
- JAVA
- C
- C++
- PYTHON
---

**Comment by Anubha13kumari** [comment]
I want to work on this please assign me @Sinjini46

**Comment by shubhamSM1298** [comment]
pls check my PR #82
