### ISSUE TITLE
Fibonacci Series

### ISSUE THREAD

**Issue by Sinjini46** [Suranjan2002/Hacktoberfest-2021-contribute#57]
You're given an integer **N**. Write a program to display the  **Fibonacci** series upto the **Nth** term.\
\
A **Fibonacci** series is a sequence of numbers where the next number is the sum of previous two numbers The first two numbers of **Fibonacci** series are 0 and 1. The **Fibonacci** numbers are the numbers in the following integer sequence. \
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ……..

---
### Input
The first line contains an integer **T**, the total number of test cases. Then follow **T** lines, each line contains an integer **N**.

---
### Output
For each test case, display the **Fibonacci** series upto the **Nth** term.

---
### Constraints
- 1 **≤ T ≤** 100
- 1 **≤ N ≤** 1000

---
### Example
**Input**
```
3 
4
8
15
```
**Output**
```
0 1 1 2
0 1 1 2 3 5 8 13
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377
```
---
### Languages	
- JAVA
- C
- C++
- PYTHON
---

**Comment by Aniket-Srivastava-21** [comment]
I can do it in C++/C/Python. Please assign it to me @Sinjini46

**Comment by sumitmohite0501** [comment]
Please assign this to me
