### ISSUE TITLE
Niven Number

### ISSUE THREAD

**Issue by Sinjini46** [Suranjan2002/Hacktoberfest-2021-contribute#66]
You're given an integer **N**. Write a program to check whether the integer is a **Niven** number or not.

A number is said to be a **Niven**  number when the number is divisible by the sum of its digits.

---
### Input
The first line contains an integer **T**, the total number of test cases. Then follow **T** lines, each line contains an integer **N**.

---
### Output
For each test case, check whether the number is **"Niven"** or not. If true, then display **"Niven Number"**, otherwise, display **“Not a Niven Number”**, in a new line (quotes for clarity).

---
### Constraints
•	1 **≤ T ≤** 100
•	1 **≤ N ≤** 1000

---
### Input
```
3 
18
15
1729
```
### Output
```
Niven Number
Not a Niven Number
Niven Number
```
---
### Languages
•	JAVA
•	C
•	C++
•	PYTHON

**Comment by iaryangoyal** [comment]
I would like to do this
@Sinjini46

**Comment by Akhilesh0947** [comment]
please approve #67

**Comment by Akhilesh0947** [comment]
please approve #66

**Comment by Akhilesh0947** [comment]
please approve  #69

**Comment by shubhamSM1298** [comment]
pls Check my PR #81

**Comment by mohitahlawat2001** [comment]
i want to do this in cpp.
